### ISSUE TITLE
Increasing attribute as advance generates advance but doesn't increase the attribute

### ISSUE THREAD

**Issue by mhilbrunner** [kristianserrano/swade-item-tables-issue-tracker#17]
As title. Haven't tested yet if it works with english locale, but AFAIK that shouldn't make a difference.

Also I'm fairly sure this *used* to work, not sure when it broke.

**Comment by kristianserrano** [comment]
I was able to reproduce this. I'll get a fix in for this soon.

**Comment by kristianserrano** [comment]
Fixed in 1.21.10
