### ISSUE TITLE
Bug: Only the first Skill, Hindrance etc. can be deleted

### ISSUE THREAD

**Issue by mhilbrunner** [kristianserrano/swade-item-tables-issue-tracker#4]
If I add multiple skills, hindrances etc., only the first one can be deleted. I can delete all, one after the other, but can't delete e.g. the last one before I have deleted all others.

I attached an exported actor that was freshly created. For example, it had two skills added (excuse the german): "Fahrzeug" (vehicle) and "Fokus" (focus). I can delete the former, but pressing delete on the latter does not work until I deleted the former.

[fvtt-Actor-test-akEJjdv6zjz7ISdV.zip](https://github.com/kristianserrano/swade-item-tables-issue-tracker/files/15160007/fvtt-Actor-test-akEJjdv6zjz7ISdV.zip)

**Comment by kristianserrano** [comment]
I found the issue. I was using `querySelector` and adding the event listener to just one instance of the delete buttons instead of `querySelectorAll` and looping to add the event listeners to all of them. Honestly, I don't know how this hasn't come up sooner. Rolling out a fix soon.

**Comment by kristianserrano** [comment]
Fixed and released v1.15.7!

**Comment by mhilbrunner** [comment]
Thank you, that was amazingly quick, and thanks for the awesome module 🙏

**Comment by kristianserrano** [comment]
You're absolutely welcome, and thank _you_! 

By the way, dropped a comment regarding submitting items 1 and 2 regarding localization. Basically, if you can create an issue for each, I'd appreciate it.
