### ISSUE TITLE
Strange appearance of skills

### ISSUE THREAD

**Issue by peterprokurist** [kristianserrano/swade-item-tables-issue-tracker#6]
For me the skills are displayed strangely. The name of the skill on the left, huge dice icons on the right.

![image](https://github.com/kristianserrano/swade-item-tables-issue-tracker/assets/115837717/15276a95-1cb2-4770-ab30-81a6f7e4509b)

I use Foundry 11.315, SWADE 3.3.11 and Item Tables 1.16.0.
Only the SWADE core rules and item tables are activated.

![image](https://github.com/kristianserrano/swade-item-tables-issue-tracker/assets/115837717/40fa23e0-cbce-41b1-88a4-337e388751e7)

But even if I deactivate the SWADE Core Rules, the problem still persists.

**Comment by kristianserrano** [comment]
Fixed! Hard to find but easy to fix! It was an issue with the syntax of some nested CSS. New browsers don't require an `&` before nested CSS selectors, but older ones do. I had to places where the `&` was missing. Adding them in fixed the issue.
