### ISSUE TITLE
Dragging a skill multiple times to the same actor does not suppress the skill sheet

### ISSUE THREAD

**Issue by bloy** [kristianserrano/swade-item-tables-issue-tracker#7]
The skill sheet is not suppressed when a skill is dragged from SIT to an actor, after the first time for a skill and an actor. This does not reset when the SIT application is closed and reopened. It *does* reset when reloading foundry.

Steps to reproduce:
1. Open an actor sheet
2. Open SIT
3. Drag Driving at d8 to the actor sheet. Observe that the skill sheet rendering is suppressed as expected.
4. Delete Driving from the actor
5. Drag Driving at d6 to the actor sheet. Observe that the skill sheet IS rendered.

Environment:
- Foundry v12.328
- SWADE 4.0.3

This is an obscure one that probably doesn't come up much, but... well, it's weird.

**Comment by kristianserrano** [comment]
Fixed this in 1.18.3. If you're still seeing this happen in that release, please feel free to reopen this ticket.
